<a href="https://colab.research.google.com/github/Infinitylogo/fake-news-analysis/blob/master/fake_news.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Book5.csv')
df.head()

Unnamed: 0  id              domain  ... tags summary source
0           0   2       express.co.uk  ...  NaN     NaN    NaN
1           1   6  barenakedislam.com  ...  NaN     NaN    NaN
2           2   7  barenakedislam.com  ...  NaN     NaN    NaN
3           3   8  barenakedislam.com  ...  NaN     NaN    NaN
4           4   9  barenakedislam.com  ...  NaN     NaN    NaN

[5 rows x 17 columns]

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
import itertools
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.linear_model import PassiveAggressiveClassifier
import os

In [5]:
labels=df.type
labels.head()

0    rumor
1     hate
2     hate
3     hate
4     hate
Name: type, dtype: object

In [6]:
x_train,x_test,y_train,y_test=train_test_split(df['content'], labels, test_size=0.2, random_state=7)

In [7]:
#Applying tfidf to the data set
tfidf_vect = TfidfVectorizer(stop_words = 'english')
tfidf_train = tfidf_vect.fit_transform(x_train)
tfidf_test = tfidf_vect.transform(x_test)
tfidf_df = pd.DataFrame(tfidf_train.A, columns=tfidf_vect.get_feature_names())

In [8]:
y_train.unique()

array(['conspiracy', 'fake', 'clickbait', 'satire', 'unreliable',
       'junksci', 'hate', 'reliable', 'political', 'bias', 'rumor'],
      dtype=object)

In [9]:
clf = MultinomialNB() 
clf.fit(tfidf_train, y_train)                       # Fit Naive Bayes classifier according to X, y
pred = clf.predict(tfidf_test)                     # Perform classification on an array of test vectors X.
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)
print(cm)

accuracy:   0.540
[[  0   0  24   4   0   0   0   0   0   0   0]
 [  0   0  27  11   0   0   0   0   0   0   0]
 [  0   0 273  13   0   0   0   0   0   0   0]
 [  0   0  53 244   0   0   0   0   0   0   0]
 [  0   0  54   3   9   0   0   0   0   0   0]
 [  0   0  23  17   0   0   0   0   0   0   0]
 [  0   0  46   8   0   0   6   0   0   0   0]
 [  0   0  39   4   0   0   0   0   0   0   0]
 [  0   0   6   8   0   0   0   0   0   0   0]
 [  0   0  24   5   0   0   0   0   0   0   0]
 [  0   0  73  17   0   0   0   0   0   0   7]]


In [10]:
linear_clf = PassiveAggressiveClassifier(max_iter=1000, random_state=0)
linear_clf.fit(tfidf_train, y_train)
pred = linear_clf.predict(tfidf_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)
print(cm)

accuracy:   0.832
[[ 23   0   1   0   0   1   1   1   0   1   0]
 [  0  27   5   3   0   0   0   0   1   0   2]
 [  0   1 262   8   1   2   3   0   0   3   6]
 [  0   3  13 275   2   0   0   0   0   3   1]
 [  0   0   6   2  54   1   0   0   0   0   3]
 [  0   0   8   7   0  19   0   0   0   2   4]
 [  1   2   6   3   1   0  39   5   0   1   2]
 [  2   2   1   2   0   0   4  27   0   2   3]
 [  0   1   2   1   0   0   0   0  10   0   0]
 [  0   0   4   0   0   0   1   0   0  22   2]
 [  1   1  13   4   1   1   1   2   0   1  72]]
